export type PortfolioCategory =
  | 'pos-displays'
  | 'food-packaging'
  | 'alcohol-packaging'
  | 'cosmetics-packaging'
  | 'custom-packaging'

export interface PortfolioItem {
  src: string
  alt: string
  altBg: string
  category: PortfolioCategory
  // Real pixel dimensions of the optimized file, used to render each gallery
  // tile at its true aspect ratio (no cropping/distortion) in PortfolioGrid.tsx.
  width: number
  height: number
  // Subgroup heading (e.g. "Floor Displays"), set only for categories in
  // categoriesWithGroupHeadings below. PortfolioGrid.tsx renders one whenever
  // this differs from the previous tile's group.
  group?: string
  groupBg?: string
}

// GENERATED FILE — do not edit by hand.
// Source of truth: scripts/portfolio-manifest.mjs
// Regenerate with:
//   node scripts/optimize-portfolio-images.mjs
//   node scripts/generate-portfolio-data.mjs
export const portfolioItems: PortfolioItem[] = [
  // POS Displays (52)
  { src: '/assets/portfolio/pos-displays/pos-displays-hero-v2.jpg', alt: 'Three black FIFA World Cup 2026 floor display stands shown side by side — one filled with footballs, one empty with a rainbow-striped back panel, one closed', altBg: 'Три черни подови дисплея FIFA World Cup 2026, показани един до друг — един зареден с футболни топки, един празен с дъгоцветен заден панел и един затворен', category: 'pos-displays', width: 1537, height: 1023, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-50-v2.jpg', alt: 'Black and gold Bushmills Irish Whiskey floor display with two tiers and a festive bauble pattern', altBg: 'Черно-златен подов дисплей Bushmills Irish Whiskey с два етажа и празничен десен с коледни топки', category: 'pos-displays', width: 1086, height: 1448, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-01-v2.jpg', alt: 'Pair of Golden Choice floor displays in dark green and lime, each with three shelves and a printed promotional header', altBg: 'Двойка подови дисплеи Golden Choice в тъмнозелено и лайм, всеки с три рафта и отпечатан промоционален топер', category: 'pos-displays', width: 896, height: 1600, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-07-v2.jpg', alt: 'Let the BEGIN gin floor display in white and green, topped with a cocktail photography header', altBg: 'Подов дисплей за джин Let the BEGIN в бяло и зелено, с топер с фотография на коктейли', category: 'pos-displays', width: 627, height: 1600, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-45-v2.jpg', alt: 'Fuze Tea floor display with three shelves and botanical leaf and hibiscus artwork', altBg: 'Подов дисплей Fuze Tea с три рафта и ботанически десен с листа и хибискус', category: 'pos-displays', width: 1086, height: 1448, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-46-v2.jpg', alt: 'Burgasko floor display with three shelves, a sunburst and wave design and a sailing-ship logo header', altBg: 'Подов дисплей „Бургаско“ с три рафта, дизайн със слънчеви лъчи и вълни и топер с логото с кораб', category: 'pos-displays', width: 1086, height: 1448, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-14-v2.jpg', alt: 'Pair of orange Bakandys floor displays with shaped headers and three shelves each', altBg: 'Двойка оранжеви подови дисплея Bakandys с профилирани топери и по три рафта', category: 'pos-displays', width: 960, height: 1600, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-12-v2.jpg', alt: 'Red Coca-Cola floor display with a Taste the Feeling header and a lifestyle photograph down the side panel', altBg: 'Червен подов дисплей Coca-Cola с топер Taste the Feeling и лайфстайл снимка по страничния панел', category: 'pos-displays', width: 738, height: 1600, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-03-v2.jpg', alt: 'Tall purple Cadbury Dairy Milk floor display with four shelves and gold foil branding down the side panel', altBg: 'Висок лилав подов дисплей Cadbury Dairy Milk с четири рафта и златно фолио брандиране по страничния панел', category: 'pos-displays', width: 686, height: 1600, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-04-v2.jpg', alt: 'Blue Zdrave pharmacy floor display with four shelves and a curved printed header', altBg: 'Син аптечен подов дисплей „Здраве“ с четири рафта и извит отпечатан топер', category: 'pos-displays', width: 813, height: 1600, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-10-v2.jpg', alt: 'Green AROMA floor display with four shelves and vertical brand lettering on the side panel', altBg: 'Зелен подов дисплей AROMA с четири рафта и вертикален надпис на марката по страничния панел', category: 'pos-displays', width: 900, height: 1600, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-13-v2.jpg', alt: 'Alvina floor display in white and kraft with four shelves and a full-height lifestyle photograph', altBg: 'Подов дисплей Alvina в бяло и крафт с четири рафта и лайфстайл фотография по цялата височина', category: 'pos-displays', width: 822, height: 1600, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-39-v2.jpg', alt: 'Tall Grivas Organic Food floor display with a pistachio photograph header and four wood-print shelves stocked with coffee and nut packs', altBg: 'Висок подов дисплей Grivas Organic Food с топер със снимка на шам-фъстък и четири рафта с дървесен принт, заредени с пакети кафе и ядки', category: 'pos-displays', width: 1086, height: 1448, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-42-v2.jpg', alt: 'Pink Bulgarian Rose Lady\'s Joy floor display with four shelves and a die-cut rose header', altBg: 'Розов подов дисплей Bulgarian Rose Lady\'s Joy с четири рафта и щанцован топер с рози', category: 'pos-displays', width: 1190, height: 1322, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-49-v2.jpg', alt: 'Orange Cappy Pulpy floor display with four shelves and a die-cut juice-splash header', altBg: 'Оранжев подов дисплей Cappy Pulpy с четири рафта и щанцован топер с пръски сок', category: 'pos-displays', width: 1086, height: 1448, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-48-v2.jpg', alt: 'Orange and white children\'s toy floor display with four shelves and cartoon animal and doll characters', altBg: 'Оранжево-бял подов дисплей за детски играчки с четири рафта и анимационни герои — животни и кукли', category: 'pos-displays', width: 1086, height: 1448, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-09-v2.jpg', alt: 'Colourful children\'s toy floor display with a cartoon header and four compartment shelves', altBg: 'Цветен подов дисплей за детски играчки с анимационен топер и четири етажа с прегради', category: 'pos-displays', width: 566, height: 1600, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-02-v2.jpg', alt: 'Fanta 2-in-1 floor display in blue and orange with a die-cut lifestyle header of a girl drinking through a straw', altBg: 'Подов дисплей Fanta 2в1 в синьо и оранжево с щанцован лайфстайл топер на момиче, което пие със сламка', category: 'pos-displays', width: 659, height: 1600, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-05-v2.jpg', alt: 'Two Healthy Food floor displays with polka-dot panels in green, purple and grey, shown from the front and the side', altBg: 'Два подови дисплея Healthy Food с панели на точки в зелено, лилаво и сиво, показани отпред и отстрани', category: 'pos-displays', width: 1190, height: 1322, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-08-v2.jpg', alt: 'Loulou Bath & Body shampoo bar floor displays in navy and white, shown in three configurations with compartment inserts', altBg: 'Подови дисплеи Loulou Bath & Body за твърд шампоан в тъмносиньо и бяло, показани в три конфигурации с прегради', category: 'pos-displays', width: 1254, height: 1254, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-11-v2.jpg', alt: 'Two black Cremozzo 3-in-1 coffee bin displays with full-colour product and portrait photography', altBg: 'Два черни контейнерни дисплея за кафе Cremozzo 3в1 с пълноцветна продуктова и портретна фотография', category: 'pos-displays', width: 1402, height: 1122, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-16-v2.jpg', alt: 'Two black Diamant Noir bin displays with gold rules and appetising food photography', altBg: 'Два черни контейнерни дисплея Diamant Noir със златни линии и апетитна фотография на храна', category: 'pos-displays', width: 1254, height: 1254, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-17-v2.jpg', alt: 'Orange square bin display with a pole-mounted topper sign, printed all over with confectionery photography', altBg: 'Оранжев квадратен контейнерен дисплей с табела на пилон, отпечатан изцяло със снимки на сладкарски изделия', category: 'pos-displays', width: 880, height: 1600, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-15-v2.jpg', alt: 'Holland Foodz A-frame peg display in red, white and blue with a grid of punched hanging holes', altBg: 'Дисплей Holland Foodz тип „А“ в червено, бяло и синьо с решетка от щанцовани отвори за закачане', category: 'pos-displays', width: 1122, height: 1402, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-06-v2.jpg', alt: 'Stackable yellow patterned display trays built into a five-tier tower, with three loose trays beside it', altBg: 'Подредими жълти дисплей тарелки с десен, сглобени в пететажна кула, с три отделни тарелки до нея', category: 'pos-displays', width: 1424, height: 1105, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-41-v2.jpg', alt: 'Barrel-shaped Kamenitza Staro Pivo floor display in cream with six compartments and a round 135-years anniversary topper', altBg: 'Подов дисплей Каменица „Старо пиво“ във формата на бъчва, в кремаво, с шест отделения и кръгъл топер за 135 години', category: 'pos-displays', width: 1086, height: 1448, group: 'Floor Displays', groupBg: 'Подови дисплеи', },
  { src: '/assets/portfolio/pos-displays/pos-displays-28-v2.jpg', alt: 'Unprinted black three-tier counter display with scalloped shelf fronts', altBg: 'Неотпечатан черен триетажен щанд за каса с назъбени предни ръбове на рафтовете', category: 'pos-displays', width: 1239, height: 1270, group: 'Counter Displays', groupBg: 'Дисплеи за каса', },
  { src: '/assets/portfolio/pos-displays/pos-displays-21-v2.jpg', alt: 'Purple Ibuprom Sprint Max pharmacy counter display, two tiers with a die-cut product header', altBg: 'Лилав аптечен щанд за каса Ибупром Спринт Макс, два етажа с щанцован продуктов топер', category: 'pos-displays', width: 874, height: 1600, group: 'Counter Displays', groupBg: 'Дисплеи за каса', },
  { src: '/assets/portfolio/pos-displays/pos-displays-19-v2.jpg', alt: 'Dark brown Cremozzo 3-in-1 coffee counter display with a round photographic header and stick packs on both tiers', altBg: 'Тъмнокафяв щанд за каса Cremozzo 3в1 с кръгъл фотографски топер и пакетчета на двата етажа', category: 'pos-displays', width: 1050, height: 1498, group: 'Counter Displays', groupBg: 'Дисплеи за каса', },
  { src: '/assets/portfolio/pos-displays/pos-displays-43-v2.jpg', alt: 'White two-tier Christmas counter display with a Merry Christmas header and 0.99 lv price flashes', altBg: 'Бял двуетажен щанд за каса за Коледа с топер „Весела Коледа“ и ценови стикери 0,99 лв.', category: 'pos-displays', width: 1086, height: 1448, group: 'Counter Displays', groupBg: 'Дисплеи за каса', },
  { src: '/assets/portfolio/pos-displays/pos-displays-18-v2.jpg', alt: 'Wood-print stepped counter display holding rows of hanging Christmas ornaments, with a festive Lanra header', altBg: 'Стъпаловиден щанд за каса с дървесен принт, зареден с редове коледни украси, с празничен топер Lanra', category: 'pos-displays', width: 1211, height: 1299, group: 'Counter Displays', groupBg: 'Дисплеи за каса', },
  { src: '/assets/portfolio/pos-displays/pos-displays-25-v2.jpg', alt: 'Soft pink Lactacyd counter display for intimate hygiene products, with a lifestyle photo header and a stepped product shelf', altBg: 'Нежно розов щанд за каса Lactacyd за интимна хигиена, с лайфстайл топер и стъпаловиден рафт', category: 'pos-displays', width: 1229, height: 1280, group: 'Counter Displays', groupBg: 'Дисплеи за каса', },
  { src: '/assets/portfolio/pos-displays/pos-displays-27-v2.jpg', alt: 'Yellow Cacaolat counter display with three stepped shelves, shown beside its matching folding carton', altBg: 'Жълт щанд за каса Cacaolat с три стъпаловидни рафта, показан до съответната сгъваема кутия', category: 'pos-displays', width: 1600, height: 954, group: 'Counter Displays', groupBg: 'Дисплеи за каса', },
  { src: '/assets/portfolio/pos-displays/pos-displays-22-v2.jpg', alt: 'Cream Valnuts counter display for nut butters, with two labelled jars on the front shelf', altBg: 'Кремав щанд за каса Valnuts за ядкови масла, с два етикетирани буркана на предния рафт', category: 'pos-displays', width: 1373, height: 1145, group: 'Counter Displays', groupBg: 'Дисплеи за каса', },
  { src: '/assets/portfolio/pos-displays/pos-displays-23-v2.jpg', alt: 'Burgundy nine-compartment counter display with a glossy finish and gluten-free flash stickers', altBg: 'Бордо щанд за каса с девет отделения, гланцово покритие и стикери „без глутен“', category: 'pos-displays', width: 1450, height: 1085, group: 'Counter Displays', groupBg: 'Дисплеи за каса', },
  { src: '/assets/portfolio/pos-displays/pos-displays-24-v2.jpg', alt: 'Black and gold VIP Perfumes Line counter display with a filigree pattern and a tall printed header', altBg: 'Черно-златен щанд за каса VIP Perfumes Line с филигранен десен и висок отпечатан топер', category: 'pos-displays', width: 1201, height: 1310, group: 'Counter Displays', groupBg: 'Дисплеи за каса', },
  { src: '/assets/portfolio/pos-displays/pos-displays-30-v2.jpg', alt: 'Black Nutree counter display for handmade raw bars, with bright circular graphics and a tall branded header', altBg: 'Черен щанд за каса Nutree за ръчно правени барове, с ярки кръгли графики и висок брандиран топер', category: 'pos-displays', width: 1050, height: 1498, group: 'Counter Displays', groupBg: 'Дисплеи за каса', },
  { src: '/assets/portfolio/pos-displays/pos-displays-31-v2.jpg', alt: 'Three green price-point counter displays in different widths, loaded with greeting cards and small gift items', altBg: 'Три зелени щанда за каса с единна цена в различни ширини, заредени с картички и малки подаръчни артикули', category: 'pos-displays', width: 1407, height: 1118, group: 'Counter Displays', groupBg: 'Дисплеи за каса', },
  { src: '/assets/portfolio/pos-displays/pos-displays-40-v2.jpg', alt: 'Kamenitza Fresh counter display in pale yellow with a citrus and water-splash header and two round bottle cut-outs', altBg: 'Щанд за каса Kamenitza Fresh в бледожълто с топер с цитруси и водни пръски и два кръгли отвора за бутилки', category: 'pos-displays', width: 1086, height: 1448, group: 'Counter Displays', groupBg: 'Дисплеи за каса', },
  { src: '/assets/portfolio/pos-displays/pos-displays-51-v2.jpg', alt: 'Blue Alaska Vodka counter display tray with a mountain photograph and a free-glass promotional header', altBg: 'Син щанд за каса Alaska Vodka с планинска снимка и промоционален топер за подарък чаша', category: 'pos-displays', width: 1086, height: 1448, group: 'Counter Displays', groupBg: 'Дисплеи за каса', },
  { src: '/assets/portfolio/pos-displays/pos-displays-29-v2.jpg', alt: 'Rubella Dental counter display in blue and white, three shelves punched for hanging toothbrushes', altBg: 'Щанд за каса Rubella Dental в синьо и бяло, с три рафта с отвори за закачане на четки за зъби', category: 'pos-displays', width: 1132, height: 1390, group: 'Counter Displays', groupBg: 'Дисплеи за каса', },
  { src: '/assets/portfolio/pos-displays/pos-displays-26-v2.jpg', alt: 'Pastel rainbow-striped counter display fitted with white plastic hooks for hanging handmade jewellery', altBg: 'Щанд за каса с пастелни дъговидни ивици и бели пластмасови закачалки за ръчно изработени бижута', category: 'pos-displays', width: 1190, height: 1322, group: 'Counter Displays', groupBg: 'Дисплеи за каса', },
  { src: '/assets/portfolio/pos-displays/pos-displays-20-v2.jpg', alt: 'Narrow yellow Jelly Pop clip-strip display with three angled pockets of gummy candy pouches', altBg: 'Тесен жълт клип-стрип дисплей Jelly Pop с три наклонени джоба с пакетчета желирани бонбони', category: 'pos-displays', width: 736, height: 1600, group: 'Counter Displays', groupBg: 'Дисплеи за каса', },
  { src: '/assets/portfolio/pos-displays/pos-displays-47-v2.jpg', alt: 'Red Coca-Cola counter display with die-cut sneaker side panels and a beach photograph promotional header', altBg: 'Червен щанд за каса Coca-Cola с щанцовани странични панели във форма на кецове и промоционален топер с плажна снимка', category: 'pos-displays', width: 1086, height: 1448, group: 'Counter Displays', groupBg: 'Дисплеи за каса', },
  { src: '/assets/portfolio/pos-displays/pos-displays-34-v2.jpg', alt: 'Two low display trays — a plain black tray and a white tray printed with a repeating red product pattern', altBg: 'Две ниски дисплей тарелки — обикновена черна и бяла с повтарящ се червен продуктов десен', category: 'pos-displays', width: 1415, height: 1112, group: 'Shelf-Ready Trays', groupBg: 'Дисплей тарелки', },
  { src: '/assets/portfolio/pos-displays/pos-displays-32-v2.jpg', alt: 'Two shelf-ready display trays side by side — a green Kaymak tray with product photography and a dark green Nasza Spizarnia tray with cut-out handles', altBg: 'Две готови за рафт дисплей тарелки една до друга — зелена тарелка Kaymak с продуктова снимка и тъмнозелена тарелка Nasza Spizarnia с изрязани дръжки', category: 'pos-displays', width: 1600, height: 600, group: 'Shelf-Ready Trays', groupBg: 'Дисплей тарелки', },
  { src: '/assets/portfolio/pos-displays/pos-displays-44-v2.jpg', alt: 'Red Malibu shelf-ready display box for dipped wafers with a chocolate-splash header', altBg: 'Червена шелф-реди дисплей кутия Malibu за тунквани вафли с топер с шоколадови пръски', category: 'pos-displays', width: 1086, height: 1448, group: 'Shelf-Ready Trays', groupBg: 'Дисплей тарелки', },
  { src: '/assets/portfolio/pos-displays/pos-displays-38-v2.jpg', alt: 'Kraft shelf-ready display tray for Hortmann Clinic sanitary pads, with a tear-away lid and a colour-coded product-range strip', altBg: 'Крафт готова за рафт дисплей тарелка за дамски превръзки Hortmann Clinic, с откъсващ се капак и цветна лента с продуктовата гама', category: 'pos-displays', width: 1600, height: 880, group: 'Shelf-Ready Trays', groupBg: 'Дисплей тарелки', },
  { src: '/assets/portfolio/pos-displays/pos-displays-36-v2.jpg', alt: 'Svetlina eclair display tray with an open corrugated interior, printed with product photography and a city illustration', altBg: 'Дисплей тарелка за еклери Svetlina с отворена вълнообразна вътрешност, с продуктова снимка и градска илюстрация', category: 'pos-displays', width: 1600, height: 876, group: 'Shelf-Ready Trays', groupBg: 'Дисплей тарелки', },
  { src: '/assets/portfolio/pos-displays/pos-displays-33-v2.jpg', alt: 'Black Solent cherry crates stacked four high beside a single open crate, printed with fruit photography', altBg: 'Черни щайги за череши Solent, подредени на четири нива до една отворена щайга, с отпечатана фотография на плодове', category: 'pos-displays', width: 1188, height: 1324, group: 'Shelf-Ready Trays', groupBg: 'Дисплей тарелки', },
  { src: '/assets/portfolio/pos-displays/pos-displays-35-v2.jpg', alt: 'Three dark wood-grain print crate trays in graduated sizes, each with cut-out carry handles', altBg: 'Три щайги-тарелки с тъмен дървесен принт в различни размери, всяка с изрязани дръжки за носене', category: 'pos-displays', width: 1600, height: 899, group: 'Shelf-Ready Trays', groupBg: 'Дисплей тарелки', },
  { src: '/assets/portfolio/pos-displays/pos-displays-37-v2.jpg', alt: 'Light blue four-tier display tray tower with a brick-wall and bird motif on the side column', altBg: 'Светлосиня четириетажна кула от дисплей тарелки с мотив на тухлена стена и птици по страничната колона', category: 'pos-displays', width: 828, height: 1600, group: 'Shelf-Ready Trays', groupBg: 'Дисплей тарелки', },

  // Food Packaging (26)
  { src: '/assets/portfolio/food-packaging/food-packaging-hero-v2.jpg', alt: 'Two Lucciola Notte Bianca cartons for double biscuits, one in cocoa brown and one in milk cream beige, each with a die-cut display window', altBg: 'Две кутии Lucciola Notte Bianca за двойни бисквити — една в какаово кафяво и една в бежово с млечен крем, всяка с щанцован прозорец', category: 'food-packaging', width: 1600, height: 777, },
  { src: '/assets/portfolio/food-packaging/food-packaging-03-v2.jpg', alt: 'Pair of small Lucciola Notte Bianca biscuit cartons standing upright, each with an oval product window', altBg: 'Двойка малки кутии за бисквити Lucciola Notte Bianca, изправени, всяка с овален продуктов прозорец', category: 'food-packaging', width: 1054, height: 1493, },
  { src: '/assets/portfolio/food-packaging/food-packaging-18-v2.jpg', alt: 'Svetlina Medenki honey cake carton in orange and purple, with an oval window and a honeycomb illustration', altBg: 'Кутия за медени сладки Svetlina Medenki в оранжево и лилаво, с овален прозорец и илюстрация на пчелна пита', category: 'food-packaging', width: 1537, height: 1023, },
  { src: '/assets/portfolio/food-packaging/food-packaging-09-v2.jpg', alt: 'Cremozzo brown sugar carton with a die-cut window, photographed with palm leaves and a bowl of cane sugar', altBg: 'Кутия за кафява захар Cremozzo с щанцован прозорец, снимана с палмови листа и купа тръстикова захар', category: 'food-packaging', width: 1254, height: 1254, },
  { src: '/assets/portfolio/food-packaging/food-packaging-06-v2.jpg', alt: 'Two wood-grain print cheese cartons with oval display windows, one for white brined cheese and one for yellow cheese', altBg: 'Две кутии с дървесен принт за сирене и кашкавал, с овални прозорци за визуализация', category: 'food-packaging', width: 1557, height: 1010, },
  { src: '/assets/portfolio/food-packaging/food-packaging-24-v2.jpg', alt: 'Kraft corrugated coffee capsule box with a navy line illustration of a coffee branch', altBg: 'Крафт вълнообразна кутия за кафе капсули с тъмносиня линейна илюстрация на клонка кафе', category: 'food-packaging', width: 1086, height: 1448, },
  { src: '/assets/portfolio/food-packaging/food-packaging-23-v2.jpg', alt: 'Tender Food sous-vide ready meal carton in white and amber for Thai chicken curry with basmati rice, 340g', altBg: 'Картонена опаковка Tender Food за готово ястие sous vide в бяло и кехлибарено — пилешко тай-къри с ориз басмати, 340 г', category: 'food-packaging', width: 1086, height: 1448, },
  { src: '/assets/portfolio/food-packaging/food-packaging-04-v2.jpg', alt: 'Popimoni patisserie box photographed from above, dark brown with a gold pattern and an ornate label', altBg: 'Сладкарска кутия Попимони, снимана отгоре — тъмнокафява със златен десен и орнаментиран етикет', category: 'food-packaging', width: 1086, height: 1448, },
  { src: '/assets/portfolio/food-packaging/food-packaging-12-v2.jpg', alt: 'Popimoni chocolate box with a fitted moulded insert, shown with its lid and printed wrapping papers', altBg: 'Кутия за шоколадови бонбони Попимони с монтирана вложка, показана с капака и отпечатани опаковъчни хартии', category: 'food-packaging', width: 1238, height: 1271, },
  { src: '/assets/portfolio/food-packaging/food-packaging-14-v2.jpg', alt: 'Cupffee edible coffee cup cartons in three stacked sizes, beside a slim carton of coffee stirrer sticks', altBg: 'Кутии Cupffee за ядливи чаши за кафе в три подредени размера, до тънка кутия с бъркалки за кафе', category: 'food-packaging', width: 1030, height: 1527, },
  { src: '/assets/portfolio/food-packaging/food-packaging-01-v2.jpg', alt: 'Open Butcher Grill Bus burger box with cartoon street-food illustrations in red and green', altBg: 'Отворена кутия за бургер Butcher Grill Bus с анимационни илюстрации на улична храна в червено и зелено', category: 'food-packaging', width: 1142, height: 1378, },
  { src: '/assets/portfolio/food-packaging/food-packaging-07-v2.jpg', alt: 'Butcher Grill Bus burger box shown open and closed, printed edge to edge with cartoon graphics', altBg: 'Кутия за бургер Butcher Grill Bus, показана отворена и затворена, с анимационни графики по цялата повърхност', category: 'food-packaging', width: 1600, height: 951, },
  { src: '/assets/portfolio/food-packaging/food-packaging-10-v2.jpg', alt: 'Black Wurzol premium carton with gold detailing and vertical cut-out windows revealing a bottle of seasoned oil', altBg: 'Черна луксозна кутия Wurzol със златни детайли и вертикални изрязани прозорци, разкриващи бутилка подправено олио', category: 'food-packaging', width: 1212, height: 1297, },
  { src: '/assets/portfolio/food-packaging/food-packaging-02-v2.jpg', alt: 'Conago Produce gable-top smoothie pack in magenta and lilac, with a die-cut window showing frozen berries and dragon fruit', altBg: 'Кутия за смути Conago Produce тип „gable-top“ в маджента и люляк, с щанцован прозорец с замразени горски плодове и драконов плод', category: 'food-packaging', width: 1216, height: 1294, },
  { src: '/assets/portfolio/food-packaging/food-packaging-21-v2.jpg', alt: 'Green Stay Well gable-top carton for organic apple cider vinegar, with a white circular logo and an apple illustration', altBg: 'Зелена кутия Stay Well тип „gable-top“ за био ябълков оцет, с бяло кръгло лого и илюстрация на ябълка', category: 'food-packaging', width: 1321, height: 1191, },
  { src: '/assets/portfolio/food-packaging/food-packaging-15-v2.jpg', alt: 'Tonton Pierrot gable-top carton for marshmallow macarons, in pastel yellow and blue with a display window', altBg: 'Кутия Tonton Pierrot тип „gable-top“ за маршмелоу макарони, в пастелно жълто и синьо с прозорец за визуализация', category: 'food-packaging', width: 1049, height: 1499, },
  { src: '/assets/portfolio/food-packaging/food-packaging-16-v2.jpg', alt: 'Popimoni dome-shaped pastry carrier in chocolate brown with a gold polka-dot pattern and a pink tab closure', altBg: 'Куполна сладкарска кутия Попимони в шоколадово кафяво със златни точки и розово езиче за затваряне', category: 'food-packaging', width: 1498, height: 1050, },
  { src: '/assets/portfolio/food-packaging/food-packaging-17-v2.jpg', alt: 'ScrapCooking Rainbow Cake baking kit carton with a Euro-slot hang tab and a photograph of a layered rainbow cake', altBg: 'Кутия за комплект за печене ScrapCooking Rainbow Cake с евро отвор за закачане и снимка на многопластова цветна торта', category: 'food-packaging', width: 1065, height: 1477, },
  { src: '/assets/portfolio/food-packaging/food-packaging-19-v2.jpg', alt: 'Kraft brown sugar multipack dispenser carton with a tear-open front and a promotional bonus-sachets flash', altBg: 'Крафт диспенсър кутия за мултипак кафява захар с откъсваща се предна част и промоционален надпис за бонус пакетчета', category: 'food-packaging', width: 1103, height: 1426, },
  { src: '/assets/portfolio/food-packaging/food-packaging-11-v2.jpg', alt: 'Yellow Change protein brownie packaging — a flat sleeve, a folded wrap and an open counter display box', altBg: 'Жълта опаковка за протеиново брауни Change — плосък ръкав, сгъната обвивка и отворена щандова кутия', category: 'food-packaging', width: 1600, height: 900, },
  { src: '/assets/portfolio/food-packaging/food-packaging-13-v2.jpg', alt: 'Cremozzo 3-in-1 coffee range — a counter display box, a folding carton and stick packs laid out together', altBg: 'Гама Cremozzo 3в1 за кафе — щандова кутия, сгъваема опаковка и пакетчета, подредени заедно', category: 'food-packaging', width: 1600, height: 941, },
  { src: '/assets/portfolio/food-packaging/food-packaging-05-v2.jpg', alt: 'Svetlina Maronche biscuit cartons in blue and yellow, shown with the matching shelf-ready display tray', altBg: 'Кутии за бисквити Svetlina Марончче в синьо и жълто, показани със съответната готова за рафт дисплей тарелка', category: 'food-packaging', width: 1442, height: 1091, },
  { src: '/assets/portfolio/food-packaging/food-packaging-08-v2.jpg', alt: 'Yellow Toblerone shelf-ready carton shown closed and opened into a counter display tray', altBg: 'Жълта готова за рафт кутия Toblerone, показана затворена и отворена като щандова дисплей тарелка', category: 'food-packaging', width: 1145, height: 1374, },
  { src: '/assets/portfolio/food-packaging/food-packaging-20-v2.jpg', alt: 'Red Be Cola six-pack basket carrier for 330 ml bottles, with a wraparound logo print', altBg: 'Червен носач-кошница Be Cola за шест бутилки по 330 мл, с лого принт по цялата обиколка', category: 'food-packaging', width: 1254, height: 1254, },
  { src: '/assets/portfolio/food-packaging/food-packaging-22-v2.jpg', alt: 'Vereya yogurt promotional multipack carton in yellow and blue, with a die-cut window and a carry handle', altBg: 'Промоционална мултипак кутия за кисело мляко Верея в жълто и синьо, с щанцован прозорец и дръжка за носене', category: 'food-packaging', width: 1327, height: 1185, },
  { src: '/assets/portfolio/food-packaging/food-packaging-25-v2.jpg', alt: 'Yellow Healty bag-in-box carton for cold-pressed apple juice with a die-cut carry handle', altBg: 'Жълта bag-in-box кутия Healty за студено пресован ябълков сок с щанцована дръжка за носене', category: 'food-packaging', width: 1086, height: 1448, },

  // Alcohol Packaging (38)
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-hero-v2.jpg', alt: 'Three matte black Zitara single-bottle wine boxes with copper foil lettering, one standing open', altBg: 'Три матово черни кутии Zitara за една бутилка вино с медно фолио, една от които е отворена', category: 'alcohol-packaging', width: 1600, height: 828, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-01-v2.jpg', alt: 'Two black Zagreus and Svishtov Winery single-bottle gift boxes with gold foil diagonals, one open to show the kraft interior', altBg: 'Две черни подаръчни кутии за една бутилка Zagreus и Svishtov Winery със златни диагонали, едната отворена с видима крафт вътрешност', category: 'alcohol-packaging', width: 1058, height: 1487, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-02-v2.jpg', alt: 'Vinica and Dragomir bottle boxes in black, grey and orange, one open with a bottle of red wine inside', altBg: 'Кутии за бутилки Vinica и Dragomir в черно, сиво и оранжево, една отворена с бутилка червено вино вътре', category: 'alcohol-packaging', width: 1586, height: 992, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-04-v2.jpg', alt: 'Five slim single-bottle cartons in a row, from a black-and-gold ouzo pack to a pink heart-window rose wine pack', altBg: 'Пет тесни кутии за една бутилка в редица — от черно-златна опаковка за узо до розова опаковка за розе с прозорче сърце', category: 'alcohol-packaging', width: 1540, height: 1021, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-05-v2.jpg', alt: 'Kraft corrugated wedge-shaped wine carrier with a cut-out handle, holding a dark bottle', altBg: 'Крафт вълнообразен клиновиден носач за вино с изрязана дръжка, с поставена тъмна бутилка', category: 'alcohol-packaging', width: 1342, height: 1172, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-03-v2.jpg', alt: 'Tall black Millesimato single-bottle carrier with a die-cut top handle and a patterned label', altBg: 'Висок черен носач Millesimato за една бутилка с щанцована горна дръжка и етикет с десен', category: 'alcohol-packaging', width: 829, height: 1600, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-33-v2.jpg', alt: 'Black Zagreus Winery Vinica Enoteca carry case with orange foil scrollwork and a die-cut handle', altBg: 'Черна кутия-куфар Zagreus Winery Vinica Enoteca с оранжеви фолирани орнаменти и щанцована дръжка', category: 'alcohol-packaging', width: 1086, height: 1448, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-30-v2.jpg', alt: 'Black gloss single-bottle wine box with a gold foil monogram and a spot-varnish pattern', altBg: 'Черна гланцова кутия за една бутилка вино със златен фолиран монограм и лаков десен', category: 'alcohol-packaging', width: 1086, height: 1448, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-31-v2.jpg', alt: 'Black Chateau Dionis single-bottle box with gold foil lettering, a gold-lined interior and a full-height window', altBg: 'Черна кутия Chateau Dionis за една бутилка със златен фолиран надпис, златна вътрешност и прозорец по цялата височина', category: 'alcohol-packaging', width: 1086, height: 1448, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-14-v2.jpg', alt: 'Kraft Kosharite rakia gift box with die-cut bottle and glass windows, revealing the spirit bottle inside', altBg: 'Крафт подаръчна кутия за ракия Кошарите с щанцовани прозорци във форма на бутилка и чаша, разкриващи бутилката вътре', category: 'alcohol-packaging', width: 1015, height: 1549, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-15-v2.jpg', alt: 'Cycle wine gift box with circular cut-out windows and a vintage penny-farthing illustration', altBg: 'Подаръчна кутия за вино Cycle с кръгли изрязани прозорци и ретро илюстрация на високо колело', category: 'alcohol-packaging', width: 1173, height: 1341, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-21-v2.jpg', alt: 'Finlandia vodka gift box with icy blue graphics and cut-out windows for the bottle and two glasses', altBg: 'Подаръчна кутия за водка Finlandia с ледено сини графики и изрязани прозорци за бутилката и две чаши', category: 'alcohol-packaging', width: 1095, height: 1437, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-22-v2.jpg', alt: 'Jim Beam gift box with a wood-plank print and a die-cut window framing the bourbon bottle', altBg: 'Подаръчна кутия Jim Beam с принт на дървени дъски и щанцован прозорец, който рамкира бутилката бърбън', category: 'alcohol-packaging', width: 1072, height: 1467, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-17-v2.jpg', alt: 'Black and gold spirits presentation box opened to reveal a metallic gold lined interior', altBg: 'Черно-златна презентационна кутия за спиртни напитки, отворена с металик златна вътрешна облицовка', category: 'alcohol-packaging', width: 1101, height: 1429, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-23-v2.jpg', alt: 'White Stella Artois gift box with an embossed pattern, a top carry handle and a window showing the chalice glass', altBg: 'Бяла подаръчна кутия Stella Artois с релефен десен, горна дръжка за носене и прозорец, показващ чашата', category: 'alcohol-packaging', width: 1200, height: 1311, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-06-v2.jpg', alt: 'Two burgundy Nessebar two-bottle carriers with arched cut-out windows, gold foil crests and top handles', altBg: 'Два бордо носача Nessebar за две бутилки с арковидни изрязани прозорци, златни емблеми и горни дръжки', category: 'alcohol-packaging', width: 1174, height: 1340, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-19-v2.jpg', alt: 'Kraft Staropramen 150th anniversary two-bottle carrier with a green plastic handle and circular cut-out windows', altBg: 'Крафт носач за две бутилки Staropramen за 150-годишнина, със зелена пластмасова дръжка и кръгли изрязани прозорци', category: 'alcohol-packaging', width: 1159, height: 1358, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-34-v2.jpg', alt: 'Kraft two-bottle wine carrier with a Hand Made script print, a die-cut handle and two arched windows', altBg: 'Крафт носач за две бутилки вино с ръкописен надпис Hand Made, щанцована дръжка и два сводести прозореца', category: 'alcohol-packaging', width: 1086, height: 1448, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-36-v2.jpg', alt: 'Kraft Bratanov Family Winery two-bottle carrier box with a die-cut handle', altBg: 'Крафт кутия-носач Bratanov Family Winery за две бутилки с щанцована дръжка', category: 'alcohol-packaging', width: 1086, height: 1448, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-37-v2.jpg', alt: 'Grey and pink lavarose two-bottle wine box from Damianitza Winery with a black ink illustration', altBg: 'Сиво-розова кутия lavarose за две бутилки вино от Damianitza Winery с черна илюстрация с туш', category: 'alcohol-packaging', width: 1086, height: 1448, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-18-v2.jpg', alt: 'Best of Belgium 3+1 beer carrier with a top handle and moulded bottle compartments, branded for Leffe and Hoegaarden', altBg: 'Носач за бира Best of Belgium 3+1 с горна дръжка и оформени прегради за бутилки, брандиран за Leffe и Hoegaarden', category: 'alcohol-packaging', width: 1236, height: 1273, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-25-v2.jpg', alt: 'Two bottle carriers with top handles — a black Popova Kula Winery two-bottle box and a pink Poison three-bottle box with arched windows', altBg: 'Два носача за бутилки с горни дръжки — черен за две бутилки Popova Kula Winery и розов за три бутилки Poison с арковидни прозорци', category: 'alcohol-packaging', width: 1482, height: 1061, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-32-v2.jpg', alt: 'White and gold Stella Artois limited edition gift pack for three 50cl bottles and a chalice glass, with a die-cut chalice window', altBg: 'Бяло-златна подаръчна опаковка Stella Artois лимитирана серия за три бутилки 50 сл и бокал, с щанцован прозорец във формата на бокал', category: 'alcohol-packaging', width: 1086, height: 1449, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-29-v2.jpg', alt: 'Green Kamenitza six-bottle carrier with a die-cut handle, shown holding six bottles', altBg: 'Зелен кашон-носач Kamenitza за шест бутилки с щанцована дръжка, показан зареден с шест бутилки', category: 'alcohol-packaging', width: 1086, height: 1448, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-08-v2.jpg', alt: 'Two bag-in-box cartons side by side — a purple 2 L cold-pressed aronia juice pack and a white Queen\'s Winery House wine pack', altBg: 'Два bag-in-box кашона един до друг — лилав 2 л за студено пресован сок от арония и бял за вино Queen\'s Winery House', category: 'alcohol-packaging', width: 1463, height: 1075, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-09-v2.jpg', alt: 'Two 3 L bag-in-box wine cartons — a white Sandstone Gruner Veltliner pack and a kraft Angus Wine pack with a bull illustration', altBg: 'Два 3-литрови bag-in-box кашона за вино — бял Sandstone Gruner Veltliner и крафт Angus Wine с илюстрация на бик', category: 'alcohol-packaging', width: 1544, height: 1018, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-11-v2.jpg', alt: 'Dark green Yamantiev\'s 10 L bag-in-box Chardonnay carton beside a plain black bag-in-box carton', altBg: 'Тъмнозелен 10-литров bag-in-box кашон Yamantiev\'s Chardonnay до обикновен черен bag-in-box кашон', category: 'alcohol-packaging', width: 1448, height: 1086, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-35-v2.jpg', alt: 'Villa Lyubimets Traminer three-litre bag-in-box carton in green and white', altBg: 'Трилитрова bag-in-box кутия Villa Lyubimets Traminer в зелено и бяло', category: 'alcohol-packaging', width: 1086, height: 1448, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-12-v2.jpg', alt: 'Three TT bag-in-box wine cartons with sun-emblem foiling — red Syrah and Merlot, white, and rose', altBg: 'Три bag-in-box кашона за вино TT с фолио слънце-емблема — червено Syrah и Merlot, бяло и розе', category: 'alcohol-packaging', width: 1448, height: 1086, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-20-v2.jpg', alt: 'Two 3 L bag-in-box wine cartons — an elegant black-and-gold Dobroff Wine Cellar pack and a bold Rock On guitar-amp design', altBg: 'Два 3-литрови bag-in-box кашона за вино — елегантен черно-златен Dobroff Wine Cellar и дързък дизайн Rock On в стил китарен усилвател', category: 'alcohol-packaging', width: 1536, height: 1024, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-28-v2.jpg', alt: 'Pale yellow five-litre bag-in-box wine carton with a die-cut carry handle and a photograph of white and red wine glasses', altBg: 'Бледожълта петлитрова bag-in-box кутия за вино с щанцована дръжка и снимка на чаши с бяло и червено вино', category: 'alcohol-packaging', width: 1086, height: 1448, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-10-v2.jpg', alt: 'Two 5 L bag-in-box cartons for alcoholic cocktails — Strawberry Daiquiri in orange and Blue Lagoon in blue, with vivid fruit photography', altBg: 'Два 5-литрови bag-in-box кашона за алкохолни коктейли — Strawberry Daiquiri в оранжево и Blue Lagoon в синьо, с ярка фотография на плодове', category: 'alcohol-packaging', width: 1448, height: 1086, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-07-v2.jpg', alt: 'Kraft River Craft Beer box with heavy black stencil lettering and a hop-and-bottle illustration', altBg: 'Крафт кутия River Craft Beer с плътни черни надписи и илюстрация на хмел и бутилки', category: 'alcohol-packaging', width: 942, height: 1600, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-16-v2.jpg', alt: 'Navy blue The Collection rigid presentation box, shown closed and open with a gold interior and bottle slots', altBg: 'Тъмносиня твърда презентационна кутия The Collection, показана затворена и отворена със златна вътрешност и гнезда за бутилки', category: 'alcohol-packaging', width: 1600, height: 863, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-13-v2.jpg', alt: 'Magenta Fine Wine & Spirits e-commerce mailer box, shown closed and open with printed bottle compartments', altBg: 'Маджента кутия за онлайн поръчки Fine Wine & Spirits, показана затворена и отворена с отпечатани прегради за бутилки', category: 'alcohol-packaging', width: 1586, height: 992, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-24-v2.jpg', alt: 'Two Magura Winery shipping cartons in black and kraft with cave-painting artwork, one closed and one open', altBg: 'Два транспортни кашона Magura Winery в черно и крафт с мотиви от пещерни рисунки, един затворен и един отворен', category: 'alcohol-packaging', width: 1594, height: 987, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-26-v2.jpg', alt: 'White Vinoprograma wine shipping cartons, one closed and one open to show the twelve-cell bottle divider', altBg: 'Бели транспортни кашони за вино Винопрограма — един затворен и един отворен, за да се види решетката с дванадесет гнезда за бутилки', category: 'alcohol-packaging', width: 891, height: 1600, },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-27-v2.jpg', alt: 'Blue Savoy Vodka Melon shelf-ready shipper opened into a display tray, printed with a party crowd scene', altBg: 'Син готов за рафт кашон Savoy Vodka Melon, отворен като дисплей тарелка, с отпечатана сцена от парти', category: 'alcohol-packaging', width: 1395, height: 1127, },

  // Cosmetics Packaging (18)
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-hero-v2.jpg', alt: 'Line-up of nine pharmacy cartons for children\'s vitamins and herbal lozenges, including Dr. Frei Multi Vitamins and Immunity with cartoon monster characters', altBg: 'Редица от девет аптечни кутии за детски витамини и билкови близалки, включително Dr. Frei Multi Vitamins и Immunity с анимационни герои', category: 'cosmetics-packaging', width: 1600, height: 756, },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-06-v2.jpg', alt: 'Bebo baby-care cartons — a green floral SPF50 sunscreen stick multipack and a turquoise cube pack', altBg: 'Кутии за бебешка грижа Bebo — зелена с флорален десен за слънцезащитен стик SPF50 и тюркоазена кубична опаковка', category: 'cosmetics-packaging', width: 1600, height: 933, },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-04-v2.jpg', alt: 'Coral Rosa Pretiosa cartons with silver foil bands — a tall organic rose water pack and a cube-shaped natural face cream pack', altBg: 'Коралови кутии Rosa Pretiosa със сребърни фолиеви ленти — висока за органична розова вода и кубична за натурален крем за лице', category: 'cosmetics-packaging', width: 1238, height: 1271, },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-16-v2.jpg', alt: 'White and gold Celebrate Beauty carton for collagen anti-age face cream, 50ml', altBg: 'Бяло-златна кутия Celebrate Beauty за крем за лице с колаген против стареене, 50 мл', category: 'cosmetics-packaging', width: 1086, height: 1448, },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-17-v2.jpg', alt: 'Deep red Valcena Paris carton for Lift Supreme rose serum, printed edge to edge with a rose photograph', altBg: 'Наситено червена кутия Valcena Paris за розов серум Lift Supreme, с печат от край до край със снимка на роза', category: 'cosmetics-packaging', width: 1086, height: 1448, },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-09-v2.jpg', alt: 'Lady\'s Joy Luxury skincare range in white and gold cartons — serum, cleansing milk and face cream in five sizes', altBg: 'Гама за грижа за кожата Lady\'s Joy Luxury в бяло-златни кутии — серум, почистващо мляко и крем за лице в пет размера', category: 'cosmetics-packaging', width: 1158, height: 1358, },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-01-v2.jpg', alt: 'Almafirm lifting kit packaging — a reflective silver box open beside a matte black microneedling device and serum box', altBg: 'Опаковка за комплект за лифтинг Almafirm — отворена огледално сребриста кутия до матово черна кутия за микронийдлинг устройство и серум', category: 'cosmetics-packaging', width: 1599, height: 984, },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-05-v2.jpg', alt: 'Blue and white MdK master carton for 100 sterile single-use syringes, printed with product specifications', altBg: 'Синьо-бял кашон MdK за 100 стерилни спринцовки за еднократна употреба, с отпечатани продуктови спецификации', category: 'cosmetics-packaging', width: 1199, height: 1312, },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-07-v2.jpg', alt: 'Two Michelle International soap cartons with a red rose print and rectangular display windows, one shown open', altBg: 'Две кутии за сапун Michelle International с принт на червени рози и правоъгълни прозорци, едната показана отворена', category: 'cosmetics-packaging', width: 1233, height: 1275, },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-10-v2.jpg', alt: 'Blue Milucca Vanilla Babe gift carton with three die-cut windows shaped to the products inside', altBg: 'Синя подаръчна кутия Milucca Vanilla Babe с три щанцовани прозореца, оформени по продуктите вътре', category: 'cosmetics-packaging', width: 1408, height: 1117, },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-13-v2.jpg', alt: 'Pink Bulgarian Rose gift box with a rose line illustration and a cut-out window showing rose water, soap and a roll-on parfum', altBg: 'Розова подаръчна кутия Bulgarian Rose с илюстрация на роза и изрязан прозорец с розова вода, сапун и рол-он парфюм', category: 'cosmetics-packaging', width: 1503, height: 1047, },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-15-v2.jpg', alt: 'Black Evterpa Lux gift set carton for men\'s eau de parfum and deodorant, with gold script and a product window', altBg: 'Черна подаръчна кутия Evterpa Lux за мъжки парфюм и дезодорант, със златен ръкописен надпис и прозорец', category: 'cosmetics-packaging', width: 1086, height: 1448, },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-11-v2.jpg', alt: 'Three pharmacy counter display boxes for Sensodyne and Aquafresh toothpaste, shown empty and printed in white and blue', altBg: 'Три аптечни щандови дисплей кутии за паста за зъби Sensodyne и Aquafresh, показани празни в бяло и синьо', category: 'cosmetics-packaging', width: 1600, height: 900, },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-02-v2.jpg', alt: 'Three olive-green Bulgarian Rose Aromatherapy counter display boxes for glycerin soaps — closed, filled with soaps, and empty showing the six compartments', altBg: 'Три маслиненозелени щандови дисплей кутии Bulgarian Rose Aromatherapy за глицеринови сапуни — затворена, заредена със сапуни и празна с шестте отделения', category: 'cosmetics-packaging', width: 724, height: 1600, },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-03-v2.jpg', alt: 'Dusty pink Refan counter display box for handmade cosmetic soaps, with twelve compartments and a classical painting header', altBg: 'Прашно розова щандова дисплей кутия Refan за ръчно изработени козметични сапуни, с дванадесет отделения и топер с класическа картина', category: 'cosmetics-packaging', width: 1168, height: 1347, },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-12-v2.jpg', alt: 'Biovene counter display box for hyaluronic SPF50 sun serum, with a tall product header and a bottle in place', altBg: 'Щандова дисплей кутия Biovene за хиалуронов слънцезащитен серум SPF50, с висок продуктов топер и поставена опаковка', category: 'cosmetics-packaging', width: 1197, height: 1314, },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-08-v2.jpg', alt: 'Black and gold Artistea perfumery tester tray with rows of circular wells and a branded riser, holding one sample vial', altBg: 'Черно-златна тестер тарелка за парфюмерия Artistea с редици кръгли гнезда и брандиран гръб, с една мостра', category: 'cosmetics-packaging', width: 1536, height: 1024, },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-14-v2.jpg', alt: 'Open Medavita mailer box with a marbled kraft exterior and a deep purple interior carrying a gold foil message', altBg: 'Отворена куриерска кутия Medavita с мраморен крафт външен слой и наситено лилава вътрешност със златно фолио послание', category: 'cosmetics-packaging', width: 1121, height: 1403, },

  // Custom Packaging (18)
  { src: '/assets/portfolio/custom-packaging/custom-packaging-hero-v2.jpg', alt: 'Christian of Roma holiday gift box in navy with a painted bird and holly illustration, shown beside an identical box opened to a printed turquoise interior', altBg: 'Празнична подаръчна кутия Christian of Roma в тъмносиньо с рисувана птица и джел, показана до същата кутия, отворена с отпечатана тюркоазена вътрешност', category: 'custom-packaging', width: 1535, height: 1024, },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-01-v2.jpg', alt: 'Open white mailer box with a four-cell divider insert, shown with the small printed product carton it holds', altBg: 'Отворена бяла куриерска кутия с вложка от четири отделения, показана с малката отпечатана продуктова кутия, която побира', category: 'custom-packaging', width: 1530, height: 1028, },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-02-v2.jpg', alt: 'Magenta Take Care gift box with a die-cut carry handle and an embossed heart motif', altBg: 'Маджента подаръчна кутия Take Care с щанцована дръжка за носене и релефен мотив сърце', category: 'custom-packaging', width: 1193, height: 1318, },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-06-v2.jpg', alt: 'Two elongated black HKN tool boxes, one open to show the fitted foam insert and one closed with a printed spec table', altBg: 'Две продълговати черни кутии HKN за инструменти — една отворена с монтирана пенеста вложка и една затворена с отпечатана таблица със спецификации', category: 'custom-packaging', width: 1375, height: 1144, },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-13-v2.jpg', alt: 'Premium Cyxo box with a marbled grey finish, black edge banding and a die-cut top carry handle', altBg: 'Луксозна кутия Cyxo с мраморно сиво покритие, черен кант и щанцована горна дръжка за носене', category: 'custom-packaging', width: 1173, height: 1341, },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-14-v2.jpg', alt: 'Four black TCI Podium cartons in graduated sizes, with gloss-on-matte detailing and gold accent curves', altBg: 'Четири черни кутии TCI Podium в нарастващи размери, с гланц върху мат и златни акцентни извивки', category: 'custom-packaging', width: 1038, height: 1516, },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-09-v2.jpg', alt: 'Izi laundry detergent carton in blue and yellow, with daisy photography and a promotional bonus-doses flash', altBg: 'Кутия за прах за пране Изи в синьо и жълто, с фотография на маргаритки и промоционален надпис за бонус дози', category: 'custom-packaging', width: 1123, height: 1401, },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-10-v2.jpg', alt: 'White Print Green carton for a laser toner cartridge, printed with a leaf, globe and butterfly composition', altBg: 'Бяла кутия Print Green за тонер касета за лазерен принтер, с композиция от лист, глобус и пеперуда', category: 'custom-packaging', width: 1589, height: 990, },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-11-v2.jpg', alt: 'Blue and white Duralex Freshbox carton for a three-piece glass container set, with product photography on every panel', altBg: 'Синьо-бяла кутия Duralex Freshbox за комплект от три стъклени кутии, с продуктова фотография на всеки панел', category: 'custom-packaging', width: 1145, height: 1374, },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-04-v2.jpg', alt: 'Black and orange Fury Professionnel carton for professional rodent bait, with a gable top and a rat photograph', altBg: 'Черно-оранжева кутия Fury Professionnel за професионална примамка против гризачи, с двускатен връх и снимка на плъх', category: 'custom-packaging', width: 995, height: 1580, },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-08-v2.jpg', alt: 'Children\'s building-block toy packaging — two square cartons and a tall hexagonal display tube with a window', altBg: 'Опаковки за детски конструктори — две квадратни кутии и висока шестоъгълна дисплей туба с прозорец', category: 'custom-packaging', width: 1206, height: 1304, },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-12-v2.jpg', alt: 'Three retail cartons for household electric grills, each with full-colour appliance and food photography', altBg: 'Три търговски кутии за домакински електрически скари, всяка с пълноцветна фотография на уреда и храна', category: 'custom-packaging', width: 1225, height: 1284, },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-15-v2.jpg', alt: 'Three Campingaz hanging retail cartons for gas-appliance accessories, each with a die-cut hang tab and product photography', altBg: 'Три висящи търговски кутии Campingaz за аксесоари за газови уреди, всяка с щанцован отвор за закачане и продуктова снимка', category: 'custom-packaging', width: 1394, height: 1128, },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-03-v2.jpg', alt: 'Two kraft EFI Automotive cartons in different sizes, both open, printed all over with repeating brand typography', altBg: 'Две крафт кутии EFI Automotive в различни размери, и двете отворени, с повтарящ се типографски брандинг по цялата повърхност', category: 'custom-packaging', width: 1341, height: 1173, },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-05-v2.jpg', alt: 'Monbat and Start car battery cartons in three sizes, sharing a white, black and orange brand system', altBg: 'Кутии за автомобилни акумулатори Monbat и Start в три размера, с обща бяло-черно-оранжева брандинг система', category: 'custom-packaging', width: 1600, height: 945, },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-07-v2.jpg', alt: 'White and green BPY carton for a magnetic water filter, with a full-colour product photograph and warning icons', altBg: 'Бяло-зелена кутия BPY за магнитен воден филтър, с пълноцветна продуктова снимка и предупредителни икони', category: 'custom-packaging', width: 1287, height: 1222, },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-16-v2.jpg', alt: 'Two cylindrical corrugated packaging tubes — an orange and blue SKAT promotional tube and a white fluted Stella Artois tube', altBg: 'Два цилиндрични вълнообразни опаковъчни тубуса — оранжево-син промоционален тубус СКАТ и бял канелиран тубус Stella Artois', category: 'custom-packaging', width: 972, height: 1600, },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-17-v2.jpg', alt: 'Tempo shoe box with a rainbow gradient wrap and die-cut finger holes, shown closed and open', altBg: 'Кутия за обувки Tempo с дъгов градиент и щанцовани отвори за хващане, показана затворена и отворена', category: 'custom-packaging', width: 1600, height: 952, },
]

// Categories whose gallery tiles carry `group`/`groupBg` and should render
// subgroup headings (see PortfolioGrid.tsx's `showGroupHeadings` prop).
export const categoriesWithGroupHeadings: PortfolioCategory[] = [
  'pos-displays',
]
