export type PortfolioCategory =
  | 'pos-displays'
  | 'food-packaging'
  | 'alcohol-packaging'
  | 'cosmetics-packaging'
  | 'custom-packaging'

export interface PortfolioItem {
  src: string
  alt: string
  altBg: string
  category: PortfolioCategory
}

// Curated 2026-08 refresh — see the curation manifest at scripts/portfolio-manifest.mjs
// for provenance (source file, selection rationale) of every entry below.
export const portfolioItems: PortfolioItem[] = [
  // POS Displays (16)
  { src: '/assets/portfolio/pos-displays/pos-displays-hero.jpg', alt: 'Bright red two-tier cardboard floor display stand branded for Coca-Cola, with a lifestyle photo header and promotional messaging', altBg: 'Ярко червен двуетажен картонен подов дисплей за Coca-Cola, с лайфстайл снимка в горната част и промоционален текст', category: 'pos-displays' },
  { src: '/assets/portfolio/pos-displays/pos-displays-01.jpg', alt: 'Cream-colored two-tier cardboard counter display for nut butters, with two labeled jars on the front shelf', altBg: 'Кремав двуетажен картонен щанд за каса за ядкови масла, с два буркана продукт на предния рафт', category: 'pos-displays' },
  { src: '/assets/portfolio/pos-displays/pos-displays-02.jpg', alt: 'Sleek black cardboard counter display for handmade raw bars, two-tier design with colorful circular brand graphics', altBg: 'Елегантен черен картонен щанд за каса за ръчно изработени десерти, двуетажен дизайн с цветни кръгли брандирани елементи', category: 'pos-displays' },
  { src: '/assets/portfolio/pos-displays/pos-displays-03.jpg', alt: 'Pastel rainbow-striped cardboard counter display with white plastic hooks for hanging keychains and jewelry', altBg: 'Пастелен щанд за каса с дъгообразни цветни ивици и бели пластмасови закачалки за ключодържатели и бижута', category: 'pos-displays' },
  { src: '/assets/portfolio/pos-displays/pos-displays-04.jpg', alt: 'Orange vertical hanging cardboard display strip for gummy candy, wall-mounted style with multiple candy pouches attached', altBg: 'Оранжева вертикална висяща картонена лента дисплей за желирани бонбони, за монтаж на стена', category: 'pos-displays' },
  { src: '/assets/portfolio/pos-displays/pos-displays-05.jpg', alt: 'Soft pink two-tier cardboard counter display for intimate hygiene products, featuring a lifestyle photo header', altBg: 'Нежно розов двуетажен картонен щанд за каса за интимна хигиена, с лайфстайл снимка в горната част', category: 'pos-displays' },
  { src: '/assets/portfolio/pos-displays/pos-displays-06.jpg', alt: 'Vivid orange two-tier cardboard floor display for orange soda, with a large product bottle graphic and lifestyle header', altBg: 'Наситено оранжев двуетажен картонен подов дисплей за портокалова напитка, с голяма графика на бутилка', category: 'pos-displays' },
  { src: '/assets/portfolio/pos-displays/pos-displays-07.jpg', alt: 'Green two-tier cardboard floor display topped with a lifestyle cocktail photo header', altBg: 'Зелен двуетажен картонен подов дисплей с лайфстайл снимка на коктейли в горната част', category: 'pos-displays' },
  { src: '/assets/portfolio/pos-displays/pos-displays-08.jpg', alt: 'Black cardboard floor display stands with individual compartments for retail products, shown in three configurations', altBg: 'Черни картонени подови дисплеи с отделни клетки за продукти, показани в три конфигурации', category: 'pos-displays' },
  { src: '/assets/portfolio/pos-displays/pos-displays-09.jpg', alt: 'Square orange cardboard bin display with a pole-mounted topper sign, printed with confectionery product imagery', altBg: 'Квадратен оранжев картонен контейнерен дисплей с табела на пилон, отпечатан с изображения на сладкарски продукти', category: 'pos-displays' },
  { src: '/assets/portfolio/pos-displays/pos-displays-10.jpg', alt: 'Playful blue cardboard floor display with support struts, three-tier design with colorful splash graphics', altBg: 'Игрив син картонен подов дисплей с опорни елементи, триетажен дизайн с цветни графики на пръски', category: 'pos-displays' },
  { src: '/assets/portfolio/pos-displays/pos-displays-11.jpg', alt: 'Cardboard display tray for cream-filled eclairs, printed with product photography and a café scene', altBg: 'Картонена тарелка дисплей за еклери с варен крем, отпечатана с продуктова снимка и сцена от кафене', category: 'pos-displays' },
  { src: '/assets/portfolio/pos-displays/pos-displays-12.jpg', alt: 'Set of three wood-grain-print cardboard crate trays with cutout handles, in varying sizes for retail produce display', altBg: 'Комплект от три картонени тарелки-щайги с дървесен принт и изрязани дръжки, в различни размери', category: 'pos-displays' },
  { src: '/assets/portfolio/pos-displays/pos-displays-13.jpg', alt: 'Elegant black and gold cardboard display trays for premium dried cherries, shown stacked and open', altBg: 'Елегантни черно-златни картонени тарелки дисплей за premium сушени череши, показани подредени и отворени', category: 'pos-displays' },
  { src: '/assets/portfolio/pos-displays/pos-displays-14.jpg', alt: 'Light blue cardboard display tray tower for candy, four tiers stacked with a playful brick-wall graphic motif', altBg: 'Светлосиня картонена кула от тарелки дисплей за бонбони, четири етажа с игрив мотив на тухлена стена', category: 'pos-displays' },
  { src: '/assets/portfolio/pos-displays/pos-displays-15.jpg', alt: 'Two cardboard retail display trays photographed side by side, a black tray and a white tray with a red triangle pattern', altBg: 'Две картонени търговски тарелки дисплей, снимани една до друга — черна и бяла с червен триъгълен принт', category: 'pos-displays' },

  // Food Packaging (13)
  { src: '/assets/portfolio/food-packaging/food-packaging-hero.jpg', alt: 'Retail carton with Euro-slot hang tab showing a vivid rainbow-layered cake, for a baking kit product', altBg: 'Опаковка с евро отвор за закачане, показваща ярка торта с многоцветни пластове, за комплект за печене', category: 'food-packaging' },
  { src: '/assets/portfolio/food-packaging/food-packaging-01.jpg', alt: 'Gable-top smoothie pack carton with die-cut window revealing frozen berry, beetroot and dragon fruit pieces', altBg: 'Кутия за смути тип „gable-top" с щанцован прозорец, разкриващ парченца замразени плодове, цвекло и драконов плод', category: 'food-packaging' },
  { src: '/assets/portfolio/food-packaging/food-packaging-02.jpg', alt: 'Dome-shaped pastry carrier box with chocolate polka-dot pattern and pink accent panel for a patisserie brand', altBg: 'Кутия за торта с куполна форма, шоколадов десен на точки и розов акцентен панел за сладкарница', category: 'food-packaging' },
  { src: '/assets/portfolio/food-packaging/food-packaging-03.jpg', alt: 'Pair of folding cartons for double biscuits with cream filling, each with a die-cut display window', altBg: 'Два сгъваеми кутии за двойни бисквити с крем пълнеж, всяка с щанцован прозорец за визуализация', category: 'food-packaging' },
  { src: '/assets/portfolio/food-packaging/food-packaging-04.jpg', alt: 'Open corrugated burger box with colorful cartoon graphics for a grill restaurant brand', altBg: 'Отворена вълнообразна кутия за бургер с цветна анимационна графика за грил ресторант', category: 'food-packaging' },
  { src: '/assets/portfolio/food-packaging/food-packaging-05.jpg', alt: 'Folding carton for brown sugar sachets with tropical palm and sugar bowl photography', altBg: 'Сгъваема кутия за пакетчета кафява захар с фотография на палма и купа със захар', category: 'food-packaging' },
  { src: '/assets/portfolio/food-packaging/food-packaging-06.jpg', alt: 'Family of cartons for edible waffle coffee cups and coffee stirrer sticks, shown in three sizes', altBg: 'Серия кутии за ядливи вафлени кафе чаши и бъркалки за кафе, показани в три размера', category: 'food-packaging' },
  { src: '/assets/portfolio/food-packaging/food-packaging-07.jpg', alt: 'Black premium carton with cut-out window displaying a glass bottle of seasoned oil', altBg: 'Черна луксозна кутия с изрязан прозорец, показваща стъклена бутилка подправено олио', category: 'food-packaging' },
  { src: '/assets/portfolio/food-packaging/food-packaging-08.jpg', alt: 'Pair of wood-grain print cheese cartons with oval display windows, for white cheese and yellow cheese', altBg: 'Два кутии за сирене и кашкавал с дървесен десен и овален прозорец за визуализация', category: 'food-packaging' },
  { src: '/assets/portfolio/food-packaging/food-packaging-09.jpg', alt: 'Open yellow protein brownie box with bold typographic branding and product insert', altBg: 'Отворена жълта кутия за протеиново брауни с открояващ се типографски дизайн и вложка за продукта', category: 'food-packaging' },
  { src: '/assets/portfolio/food-packaging/food-packaging-10.jpg', alt: 'Gable-top carton for marshmallow macarons with pastel illustration and display window', altBg: 'Кутия тип „gable-top" за маршмелоу макарони с пастелна илюстрация и прозорец за визуализация', category: 'food-packaging' },
  { src: '/assets/portfolio/food-packaging/food-packaging-11.jpg', alt: 'Set of open counter-display boxes for fruit energy bars in grape, cherry and strawberry flavors', altBg: 'Комплект отворени кутии за щанд за плодови енергийни блокчета с вкус на грозде, череша и ягода', category: 'food-packaging' },
  { src: '/assets/portfolio/food-packaging/food-packaging-12.jpg', alt: 'Honey cake carton with oval display window and illustrated honeycomb and drizzle graphics', altBg: 'Кутия за медени сладки с овален прозорец за визуализация и илюстрация на пчелна пита и мед', category: 'food-packaging' },

  // Alcohol Packaging (13)
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-hero.jpg', alt: 'Luxury six-bottle wine gift box in navy and gold foil, open to reveal individual bottle compartments', altBg: 'Луксозна подаръчна кутия за шест бутилки вино в тъмносиньо и златно фолио, отворена да покаже отделни прегради за бутилки', category: 'alcohol-packaging' },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-01.jpg', alt: 'Single-bottle wine gift box with locking flap, open to show a bottle inside, next to three additional single-bottle box designs', altBg: 'Подаръчна кутия за една бутилка вино със закопчаващо капаче, отворена с бутилка вътре, до нея още три дизайна на кутии', category: 'alcohol-packaging' },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-02.jpg', alt: 'Single-bottle wine carrier bag in black textured laminate with die-cut handle', altBg: 'Чанта за една бутилка вино от черен текстуриран ламинат с щанцована дръжка', category: 'alcohol-packaging' },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-03.jpg', alt: 'Five single-bottle gift box designs in a row, showcasing varied colors, finishes, and cut-out windows', altBg: 'Пет дизайна на кутии за една бутилка, подредени в редица, показващи различни цветове, покрития и изрязани прозорци', category: 'alcohol-packaging' },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-04.jpg', alt: 'One-bottle and two-bottle wine gift boxes in burgundy with arched cut-out windows', altBg: 'Подаръчни кутии за една и за две бутилки вино в бордо с арковидни изрязани прозорци', category: 'alcohol-packaging' },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-05.jpg', alt: 'Ten-liter bag-in-box wine carton with pour spout and printed label graphics', altBg: '10-литров bag-in-box кашон за вино с чучур за наливане и отпечатана етикетна графика', category: 'alcohol-packaging' },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-06.jpg', alt: 'Three-liter bag-in-box wine cartons: a white-and-green design and a kraft-paper illustrated design', altBg: '3-литрови bag-in-box кашони за вино: бяло-зелен дизайн и илюстрован дизайн върху крафт хартия', category: 'alcohol-packaging' },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-07.jpg', alt: 'Five-liter bag-in-box cartons for alcoholic cocktails with vivid fruit photography', altBg: '5-литрови bag-in-box кашони за алкохолни коктейли с ярка фотография на плодове', category: 'alcohol-packaging' },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-08.jpg', alt: 'Octagonal bag-in-box wine cartons, three-liter, in red, white, and rosé variants with matching branding', altBg: 'Осемстенни bag-in-box кашони за вино, 3 литра, във варианти червено, бяло и розе с единен брандинг', category: 'alcohol-packaging' },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-09.jpg', alt: 'Three-bottle wine gift box in magenta, shown closed and open with individual cardboard dividers', altBg: 'Подаръчна кутия за три бутилки вино в цвят маджента, показана затворена и отворена с отделни картонени прегради', category: 'alcohol-packaging' },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-10.jpg', alt: 'Grape rakia gift box with die-cut bottle- and glass-shaped windows revealing the spirit bottle inside', altBg: 'Подаръчна кутия за гроздова ракия с щанцовани прозорци във форма на бутилка и чаша, разкриващи бутилката вътре', category: 'alcohol-packaging' },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-11.jpg', alt: 'Illustrated wine gift box with circular cut-out windows and vintage circus-performer artwork', altBg: 'Илюстрована подаръчна кутия за вино с кръгли изрязани прозорци и ретро цирково изкуство', category: 'alcohol-packaging' },
  { src: '/assets/portfolio/alcohol-packaging/alcohol-packaging-12.jpg', alt: 'Three-liter bag-in-box wine cartons: an elegant black-and-gold design and a bold guitar-amp-themed design', altBg: '3-литрови bag-in-box кашони за вино: елегантен черно-златен дизайн и дързък дизайн в стил китарен усилвател', category: 'alcohol-packaging' },

  // Cosmetics Packaging (10)
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-hero.jpg', alt: 'Lifting-kit cosmetics packaging — reflective silver gift box open beside a matte black microneedling kit box', altBg: 'Опаковка на комплект за лифтинг — отворена сребриста подаръчна кутия до матова черна кутия за комплект за микронийдлинг', category: 'cosmetics-packaging' },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-01.jpg', alt: 'Pink gift box for a Bulgarian Rose skincare set, with rose water, parfum roll-on and soap visible through the cut-out window', altBg: 'Розова подаръчна кутия за козметичен комплект с розова вода, парфюм рол-он и сапун, видими през прозорчето', category: 'cosmetics-packaging' },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-02.jpg', alt: 'Gold countertop tester display tray for perfumery with a single spray-bottle tester', altBg: 'Златист щандов тестер дисплей за парфюмерия с една спрей опаковка', category: 'cosmetics-packaging' },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-03.jpg', alt: 'Countertop display box for anti-aging sun serum with SPF50', altBg: 'Щандов дисплей бокс за слънцезащитен серум против стареене SPF50', category: 'cosmetics-packaging' },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-04.jpg', alt: 'Handmade rose glycerin soap boxes with die-cut window', altBg: 'Кутии за ръчно изработен глицеринов сапун с роза, с изрязано прозорче', category: 'cosmetics-packaging' },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-05.jpg', alt: 'Natural cosmetic soap counter display box with compartments', altBg: 'Щандов дисплей бокс за натурални козметични сапуни, с прегради', category: 'cosmetics-packaging' },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-06.jpg', alt: 'Organic rose water and natural face cream boxes', altBg: 'Кутии за органична розова вода и натурален крем за лице', category: 'cosmetics-packaging' },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-07.jpg', alt: 'Baby SPF50 sunscreen stick and micellar water master cartons', altBg: 'Кашони за бебешки слънцезащитен стик SPF50 и мицеларна вода', category: 'cosmetics-packaging' },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-08.jpg', alt: 'Countertop pharmacy display boxes for toothpaste brands', altBg: 'Аптечни щандови дисплей кутии за паста за зъби', category: 'cosmetics-packaging' },
  { src: '/assets/portfolio/cosmetics-packaging/cosmetics-packaging-09.jpg', alt: "Line-up of children's vitamin and herbal lozenge boxes for pharmacy brands", altBg: 'Серия кутии за детски витамини и билкови близалки на фармацевтични марки', category: 'cosmetics-packaging' },

  // Custom Packaging (14)
  { src: '/assets/portfolio/custom-packaging/custom-packaging-hero.jpg', alt: 'Rigid premium gift box with cutout carry handle and concrete-textured print', altBg: 'Луксозна твърда подаръчна кутия с изрязана дръжка за носене и бетонен принт', category: 'custom-packaging' },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-01.jpg', alt: 'Illustrated holiday gift box with festive bird print and printed thank-you interior', altBg: 'Илюстрована коледна подаръчна кутия с празничен принт на птици и благодарствена картичка отвътре', category: 'custom-packaging' },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-02.jpg', alt: 'Pink carry-handle gift box with heart-shaped logo', altBg: 'Розова подаръчна кутия с дръжка и лого във формата на сърце', category: 'custom-packaging' },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-03.jpg', alt: 'Elongated rigid box with custom foam insert for a specialty hardware product', altBg: 'Продълговата твърда кутия със специализирана вложка от пяна за нестандартен хардуерен продукт', category: 'custom-packaging' },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-04.jpg', alt: 'Set of hanging retail boxes for gas-appliance accessories with die-cut hang tab', altBg: 'Комплект кутии за окачване на щанд за аксесоари за газови уреди с изрязан отвор за закачване', category: 'custom-packaging' },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-05.jpg', alt: 'Full-color printed carton for a laser toner cartridge', altBg: 'Пълноцветна отпечатана кутия за тонер касета за лазерен принтер', category: 'custom-packaging' },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-06.jpg', alt: "Children's toy packaging in varied shapes, including a tall hexagonal display tube", altBg: 'Опаковки за детски играчки в различни форми, включително висока шестоъгълна дисплей туба', category: 'custom-packaging' },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-07.jpg', alt: 'Black and orange retail carton for professional rodent-control bait', altBg: 'Черно-оранжева опаковка за професионален препарат против гризачи', category: 'custom-packaging' },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-08.jpg', alt: 'Glossy black premium boxes for audio cable accessories with hang tabs', altBg: 'Луксозни лъскави черни кутии за аудио кабелни аксесоари с отвори за закачване', category: 'custom-packaging' },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-09.jpg', alt: 'Retail boxes for electric barbecue grills with full-color product photography', altBg: 'Търговски кутии за електрически барбекюта с пълноцветна продуктова фотография', category: 'custom-packaging' },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-10.jpg', alt: 'Automotive battery packaging in multiple sizes with consistent brand design', altBg: 'Опаковки за автомобилни акумулатори в различни размери с последователен брандинг', category: 'custom-packaging' },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-11.jpg', alt: 'Laundry detergent carton with floral graphics and top carry cutout', altBg: 'Кутия за прах за пране с флорални графики и изрязан отвор за носене отгоре', category: 'custom-packaging' },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-12.jpg', alt: 'Mailer box with playful all-over gift-themed pattern print', altBg: 'Пощенска кутия с игрив десен с подаръчна тематика по цялата повърхност', category: 'custom-packaging' },
  { src: '/assets/portfolio/custom-packaging/custom-packaging-13.jpg', alt: 'Rainbow-gradient shoe boxes with die-cut finger holes for retail display', altBg: 'Кутии за обувки с дъгообразен цветен градиент и изрязани отвори за хващане', category: 'custom-packaging' },
]
